-- supabase/migrations/20260823000009_patch_public_pii_leak.sql
-- VÁ BẢO MẬT KHẨN CẤP (P0): ĐÓNG LỖ HỔNG RÒ RỈ PII QUA CÁC RPC TRA CỨU CÔNG KHAI
--
-- Vấn đề phát hiện:
--   1. public_get_renewal_info() được GRANT cho `anon` và trả về TOÀN BỘ PII
--      (họ tên, CCCD, SĐT, ngày sinh, địa chỉ, email...) chỉ cần biết đúng
--      định dạng mã CCCD/BHXH — không giới hạn tần suất gọi (rate-limit),
--      không bắt buộc CAPTCHA ở tầng CSDL. Vì RPC được PostgREST expose công
--      khai và anon key luôn có sẵn trong bundle JS phía client, bất kỳ ai
--      cũng có thể gọi trực tiếp và vét cạn (brute-force) số CCCD để thu thập
--      hàng loạt hồ sơ cá nhân thật.
--   2. public_lookup_process() ở migration 000008 đã vô tình bỏ cơ chế che
--      (mask) tên & CCCD vốn có ở thiết kế "Zero-PII" ban đầu (migration
--      000002), trả về name/cccd dạng plaintext.
--
-- Hướng khắc phục:
--   - Thu hồi hoàn toàn quyền `anon`/`authenticated` trên public_get_renewal_info;
--     chỉ service_role (Edge Function dùng service role key, có CAPTCHA +
--     kiểm tra Origin) mới được gọi.
--   - Khôi phục việc che tên/CCCD trong public_lookup_process.
--   - Bổ sung rate-limit theo IP (giống cơ chế đã áp dụng cho
--     public_register_customer) cho MỌI RPC tra cứu công khai, để chặn tấn
--     công vét cạn kể cả khi request đi qua đúng Edge Function.

-- ======================================================================
-- 1. BẢNG GHI NHẬN LƯỢT GỌI RPC CÔNG KHAI ĐỂ RATE-LIMIT (DÙNG CHUNG)
-- ======================================================================

CREATE TABLE IF NOT EXISTS public.public_rpc_call_log (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action" TEXT NOT NULL,
  "ip_address" TEXT NOT NULL,
  "called_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_public_rpc_call_log_lookup
  ON public.public_rpc_call_log(action, ip_address, called_at DESC);

-- Dọn log cũ hơn 48h để bảng không phình to (best-effort, không bắt buộc phải chạy đúng lịch)
CREATE OR REPLACE FUNCTION public.purge_old_public_rpc_logs()
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  DELETE FROM public.public_rpc_call_log WHERE called_at < NOW() - INTERVAL '48 hours';
$$;

ALTER TABLE public.public_rpc_call_log ENABLE ROW LEVEL SECURITY;
-- Không có policy nào cho client -> mặc định KHÔNG ai đọc/ghi trực tiếp được bảng này qua REST API.
-- Chỉ các hàm SECURITY DEFINER bên dưới (chạy với quyền chủ sở hữu) mới ghi được vào bảng.

-- ======================================================================
-- 2. HÀM DÙNG CHUNG: LẤY IP CLIENT + KIỂM TRA/GHI NHẬN RATE LIMIT
-- ======================================================================

CREATE OR REPLACE FUNCTION public.get_public_client_ip()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_headers json;
  v_client_ip text := '127.0.0.1';
BEGIN
  BEGIN
    v_headers := current_setting('request.headers', true)::json;
    IF v_headers IS NOT NULL THEN
      v_client_ip := COALESCE(
        v_headers->>'cf-connecting-ip',
        split_part(v_headers->>'x-forwarded-for', ',', 1),
        '127.0.0.1'
      );
    END IF;
  EXCEPTION WHEN OTHERS THEN
    v_client_ip := '127.0.0.1';
  END;
  RETURN TRIM(v_client_ip);
END;
$$;

-- Trả về TRUE nếu vượt giới hạn (và ghi nhận lượt gọi hiện tại nếu chưa vượt).
-- Tài khoản đã đăng nhập (Admin/Quản lý/Nhân viên) luôn được bỏ qua giới hạn.
CREATE OR REPLACE FUNCTION public.enforce_public_rpc_rate_limit(
  p_action TEXT,
  p_max_calls INTEGER,
  p_window INTERVAL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_ip text;
  v_count integer;
BEGIN
  IF auth.role() = 'authenticated' THEN
    RETURN;
  END IF;

  v_ip := public.get_public_client_ip();

  SELECT COUNT(*) INTO v_count
  FROM public.public_rpc_call_log
  WHERE action = p_action
    AND ip_address = v_ip
    AND called_at >= (NOW() - p_window);

  IF v_count >= p_max_calls THEN
    RAISE EXCEPTION 'RATE_LIMIT_EXCEEDED: Địa chỉ mạng (%) đã vượt giới hạn tra cứu cho phép. Vui lòng thử lại sau.', v_ip;
  END IF;

  INSERT INTO public.public_rpc_call_log (action, ip_address) VALUES (p_action, v_ip);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.get_public_client_ip() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.enforce_public_rpc_rate_limit(TEXT, INTEGER, INTERVAL) FROM anon, public;

-- ======================================================================
-- 3. KHÔI PHỤC CHE (MASK) PII TRONG public_lookup_process + RATE LIMIT
-- ======================================================================

DROP FUNCTION IF EXISTS public.public_lookup_process(TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.public_lookup_process(p_code TEXT, p_type TEXT)
RETURNS TABLE (
  masked_name TEXT,
  masked_cccd TEXT,
  type TEXT,
  fromMonth TEXT,
  toMonth TEXT,
  months INTEGER,
  amount NUMERIC,
  nextPayment TEXT,
  status TEXT,
  paymentStatus TEXT,
  registration_date TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_code IS NULL OR TRIM(p_code) !~ '^\d{9}$|^\d{10}$|^\d{12}$' THEN
    RETURN;
  END IF;

  -- Tối đa 10 lượt tra cứu / giờ / IP đối với khách vãng lai chưa đăng nhập
  PERFORM public.enforce_public_rpc_rate_limit('public_lookup_process', 10, INTERVAL '1 hour');

  RETURN QUERY
  SELECT
    CASE
      WHEN LENGTH(r.name) > 4 THEN SUBSTRING(r.name FROM 1 FOR 2) || '*** ' || SPLIT_PART(r.name, ' ', -1)
      ELSE '***'
    END AS masked_name,
    CASE
      WHEN LENGTH(r.cccd) = 12 THEN '******' || RIGHT(r.cccd, 4)
      ELSE '******'
    END AS masked_cccd,
    COALESCE(r.type, ''),
    COALESCE(r."fromMonth", ''),
    COALESCE(r."toMonth", ''),
    COALESCE(r.months, 1),
    COALESCE(r.amount, 0),
    COALESCE(r."nextPayment"::text, ''),
    COALESCE(r.status, 'Đang tham gia'),
    COALESCE(r."paymentStatus", ''),
    COALESCE(to_char(r.date, 'YYYY-MM-DD'), '') AS registration_date
  FROM public.records r
  WHERE r."paymentStatus" != 'Đã hủy'
    AND r.type = UPPER(TRIM(p_type))
    AND (
      (r.bhxh = TRIM(p_code) AND r.bhxh IS NOT NULL AND r.bhxh != '') OR
      (r.cccd = TRIM(p_code) AND r.cccd IS NOT NULL AND r.cccd != '')
    )
  ORDER BY r.date DESC
  LIMIT 10;
END;
$$;

GRANT EXECUTE ON FUNCTION public.public_lookup_process(TEXT, TEXT) TO service_role, anon, authenticated;


-- ======================================================================
-- 4. THU HỒI HOÀN TOÀN QUYỀN ANON/AUTHENTICATED TRÊN public_get_renewal_info
--    (Chỉ được gọi thông qua Edge Function public-customer-intake bằng
--    service_role key, nơi có kiểm tra CAPTCHA + Origin whitelist).
--    Đồng thời bổ sung rate-limit phòng vệ theo chiều sâu (defense-in-depth).
-- ======================================================================

DROP FUNCTION IF EXISTS public.public_get_renewal_info(TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.public_get_renewal_info(p_code TEXT, p_type TEXT)
RETURNS TABLE (
  name TEXT,
  cccd TEXT,
  phone TEXT,
  bhxh TEXT,
  dob DATE,
  gender TEXT,
  nation TEXT,
  email TEXT,
  address TEXT,
  type TEXT,
  method TEXT,
  months INTEGER,
  income NUMERIC,
  fromMonth TEXT,
  toMonth TEXT,
  notes TEXT,
  recvName TEXT,
  recvPhone TEXT,
  recvAddress TEXT,
  members JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- Chỉ chấp nhận lời gọi có vai trò service_role (Edge Function) hoặc nhân
  -- viên/quản trị đã đăng nhập. Trực tiếp chặn vai trò `anon` gọi qua REST API.
  IF auth.role() NOT IN ('service_role', 'authenticated') THEN
    RAISE EXCEPTION 'Access denied: Chức năng gia hạn nhanh chỉ khả dụng qua cổng dịch vụ đã xác thực.';
  END IF;

  IF p_code IS NULL OR TRIM(p_code) !~ '^\d{9}$|^\d{10}$|^\d{12}$' THEN
    RETURN;
  END IF;

  -- Phòng vệ theo chiều sâu: vẫn giới hạn tần suất kể cả khi gọi qua service_role
  -- (ví dụ Edge Function bị khai thác/lạm dụng), trừ nhân viên đã đăng nhập trực tiếp.
  PERFORM public.enforce_public_rpc_rate_limit('public_get_renewal_info', 10, INTERVAL '1 hour');

  RETURN QUERY
  SELECT
    r.name,
    r.cccd,
    r.phone,
    r.bhxh,
    r.dob,
    r.gender,
    r.nation,
    r.email,
    r.address,
    r.type,
    r.method,
    r.months,
    r.income,
    r."fromMonth",
    r."toMonth",
    r.notes,
    r."recvName",
    r."recvPhone",
    r."recvAddress",
    r.members
  FROM public.records r
  WHERE r."paymentStatus" != 'Đã hủy'
    AND r.type = UPPER(TRIM(p_type))
    AND (
      (r.bhxh = TRIM(p_code) AND r.bhxh IS NOT NULL AND r.bhxh != '') OR
      (r.cccd = TRIM(p_code) AND r.cccd IS NOT NULL AND r.cccd != '')
    )
  ORDER BY r.date DESC
  LIMIT 1;
END;
$$;

-- KHÔNG grant cho anon/authenticated qua REST API trực tiếp; chỉ service_role
-- (được Edge Function sử dụng qua SUPABASE_SERVICE_ROLE_KEY phía server) và
-- người dùng đã đăng nhập nội bộ mới gọi được. PostgREST vẫn liệt kê hàm
-- trong schema nhưng vai trò anon sẽ bị từ chối bởi câu lệnh RAISE EXCEPTION
-- ở trên NẾU có ai cố gắng bypass; để chắc chắn hơn nữa ta cũng REVOKE tường minh.
REVOKE EXECUTE ON FUNCTION public.public_get_renewal_info(TEXT, TEXT) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.public_get_renewal_info(TEXT, TEXT) TO service_role, authenticated;


-- ======================================================================
-- 5. RATE-LIMIT BỔ SUNG CHO check_customer_exists (CHỐNG ENUMERATION)
-- ======================================================================

CREATE OR REPLACE FUNCTION public.check_customer_exists(p_code TEXT)
RETURNS TABLE (
  customer_exists BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_code IS NULL OR TRIM(p_code) !~ '^\d{9}$|^\d{10}$|^\d{12}$' THEN
    RETURN QUERY SELECT false AS customer_exists;
    RETURN;
  END IF;

  -- Tối đa 20 lượt kiểm tra / giờ / IP đối với khách vãng lai chưa đăng nhập
  PERFORM public.enforce_public_rpc_rate_limit('check_customer_exists', 20, INTERVAL '1 hour');

  RETURN QUERY
  SELECT EXISTS (
    SELECT 1 FROM public.records r
    WHERE r."paymentStatus" != 'Đã hủy'
      AND (
        (r.bhxh = TRIM(p_code) AND r.bhxh IS NOT NULL AND r.bhxh != '') OR
        (r.cccd = TRIM(p_code) AND r.cccd IS NOT NULL AND r.cccd != '')
      )
  ) AS customer_exists;
END;
$$;

GRANT EXECUTE ON FUNCTION public.check_customer_exists(TEXT) TO service_role, anon, authenticated;

NOTIFY pgrst, 'reload schema';
