-- ======================================================================
-- NỀN TẢNG QUẢN LÝ THU & DỊCH VỤ CÔNG BHXH / BHYT SÔNG MÃ
-- BASELINE MIGRATION 0001: BASELINE SCHEMA (DDL, CONSTRAINTS & INDEXES)
-- ======================================================================
-- Mục đích: Khởi tạo 100% CSDL Supabase PostgreSQL chuẩn hóa theo quy chuẩn
-- Naming Convention: 100% snake_case, triệt tiêu toàn bộ cột camelCase cũ.
-- Bao gồm: 10 Bảng cốt lõi + Foreign Keys + Constraints + 3 Unified Views + Indexes + Seed Data.
-- ======================================================================

-- 1. BẬT TIỆN ÍCH MÃ HÓA, UUID VÀ TÌM KIẾM TOÀN VĂN TRIGRAM
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ======================================================================
-- 2. ĐỊNH NGHĨA 10 BẢNG CƠ SỞ DỮ LIỆU CHUẨN HÓA (100% SNAKE_CASE)
-- ======================================================================

-- 2.1. Bảng nhân sự cán bộ thu (staff)
CREATE TABLE IF NOT EXISTS public.staff (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'Nhân viên',
    status TEXT NOT NULL DEFAULT 'Đang hoạt động',
    area TEXT,
    staff_code TEXT,
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    phone TEXT,
    cccd TEXT,
    username TEXT,
    permissions JSONB DEFAULT '[]'::jsonb,
    custom_permissions JSONB DEFAULT '[]'::jsonb,
    revoked_permissions JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.2. Bảng đợt nộp hồ sơ cơ quan BHXH chính quy (submission_batches)
CREATE TABLE IF NOT EXISTS public.submission_batches (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    batch_code TEXT NOT NULL UNIQUE,
    insurance_type TEXT NOT NULL DEFAULT 'BHXH', -- 'BHXH', 'BHYT', 'CA_HAI'
    status TEXT NOT NULL DEFAULT 'draft',        -- 'draft', 'submitted', 'approved', 'rejected'
    created_by TEXT REFERENCES public.staff(id) ON DELETE SET NULL,
    total_records INT NOT NULL DEFAULT 0,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    submission_date DATE,
    approval_date DATE,
    receipt_number TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.3. Bảng thiết lập hệ thống (settings)
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comm_bhxh_new NUMERIC DEFAULT 5,
    comm_bhxh_renew NUMERIC DEFAULT 3,
    comm_bhyt_new NUMERIC DEFAULT 5,
    comm_bhyt_renew NUMERIC DEFAULT 3,
    comm_bhxh NUMERIC DEFAULT 5,
    comm_bhyt NUMERIC DEFAULT 5,
    investment_rate NUMERIC DEFAULT 0.31,
    base_salary NUMERIC DEFAULT 2340000,
    poverty_standard NUMERIC DEFAULT 1500000,
    cpi_index JSONB,
    agency_name TEXT DEFAULT 'Đại lý thu BHXH Sông Mã',
    agency_code TEXT DEFAULT 'VSS-SM-001',
    bank_bin TEXT DEFAULT '970422',
    bank_id TEXT DEFAULT 'MB',
    bank_name TEXT DEFAULT 'MB (Ngân hàng Quân Đội)',
    account_number TEXT DEFAULT '0868123456',
    account_holder TEXT DEFAULT 'DAI LY THU BHXH SONG MA',
    qr_template TEXT DEFAULT 'compact2',
    role_permissions JSONB DEFAULT '{}'::jsonb,
    user_overrides JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.4. Bảng quản lý chính sách & cấu hình động (policies)
CREATE TABLE IF NOT EXISTS public.policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parameter_type TEXT NOT NULL,
    value JSONB NOT NULL,
    effective_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by TEXT,
    notes TEXT,
    description TEXT
);

-- 2.5. Bảng khách hàng danh bạ tổng hợp Master Data (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_key TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL DEFAULT 'BHXH', -- 'BHXH', 'BHYT', hoặc 'CẢ HAI'
    name TEXT NOT NULL,
    cccd TEXT,
    bhxh TEXT,
    old_bhxh TEXT,
    phone TEXT,
    address TEXT,
    dob DATE,
    gender TEXT,
    nation TEXT,
    email TEXT,
    has_bhxh BOOLEAN DEFAULT FALSE,
    has_bhyt BOOLEAN DEFAULT FALSE,
    latest_record_id BIGINT,
    latest_date DATE,
    effective_date DATE,
    next_payment DATE,
    next_payment_bhxh DATE,
    next_payment_bhyt DATE,
    latest_amount NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Đang tham gia',
    payment_status TEXT DEFAULT 'Đã thu tiền',
    notes TEXT,
    staff_id TEXT REFERENCES public.staff(id) ON DELETE SET NULL,
    total_contributions INT DEFAULT 1,
    total_amount_paid NUMERIC DEFAULT 0,
    household_id TEXT,
    members JSONB,
    recv_name TEXT,
    recv_phone TEXT,
    recv_address TEXT,
    prior_periods JSONB DEFAULT '[]'::jsonb,
    prior_voluntary_months INT DEFAULT 0,
    prior_compulsory_months INT DEFAULT 0,
    prior_participation_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.6. Bảng hồ sơ giao dịch tham gia BHXH / BHYT (records)
CREATE TABLE IF NOT EXISTS public.records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type TEXT,
    payment_status TEXT DEFAULT 'Chờ thu tiền',
    status TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    staff_id TEXT REFERENCES public.staff(id) ON DELETE SET NULL,
    name TEXT,
    cccd TEXT,
    phone TEXT,
    bhxh TEXT,
    old_bhxh TEXT,
    dob DATE,
    gender TEXT,
    nation TEXT,
    email TEXT,
    address TEXT,
    notes TEXT,
    type TEXT NOT NULL, -- 'BHXH', 'BHYT'
    sub_type TEXT,
    wage NUMERIC,
    support_pct NUMERIC,
    commission NUMERIC,
    support NUMERIC,
    household_id TEXT,
    effective_date DATE,
    target_date DATE,
    income NUMERIC,
    nn_support_pct NUMERIC,
    dp_support_pct NUMERIC,
    method TEXT,
    months INTEGER DEFAULT 1,
    from_month TEXT,
    to_month TEXT,
    from_month_date DATE,
    to_month_date DATE,
    submitted_date DATE,
    decision_date DATE,
    batch_id UUID REFERENCES public.submission_batches(id) ON DELETE SET NULL,
    submission_batch_id UUID REFERENCES public.submission_batches(id) ON DELETE SET NULL,
    submission_batch TEXT,
    base_premium NUMERIC,
    nn_support_amount NUMERIC,
    dp_support_amount NUMERIC,
    amount NUMERIC,
    discount_amount NUMERIC,
    penalty_amount NUMERIC,
    next_payment DATE,
    members JSONB,
    recv_name TEXT,
    recv_phone TEXT,
    recv_address TEXT,
    ip_address TEXT,
    is_submitted_bhxh BOOLEAN DEFAULT FALSE,
    base_salary_snapshot NUMERIC,
    poverty_standard_snapshot NUMERIC,
    policy_version_id BIGINT,
    applied_rates JSONB,
    is_adjustment BOOLEAN DEFAULT FALSE,
    original_record_id BIGINT,
    adjustment_reason TEXT,
    customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_key TEXT,
    idempotency_key TEXT,
    refund_type TEXT,
    decision_number TEXT,
    refund_method TEXT,
    refund_beneficiary_name TEXT,
    refund_beneficiary_account TEXT,
    refund_beneficiary_bank TEXT,
    hospital_code TEXT,
    hospital_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Khóa ngoại ngược từ customers sang records (latest_record_id)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_customers_latest_record'
    ) THEN
        ALTER TABLE public.customers 
        ADD CONSTRAINT fk_customers_latest_record 
        FOREIGN KEY (latest_record_id) REFERENCES public.records(id) ON DELETE SET NULL;
    END IF;
END $$;

-- 2.7. Bảng chi tiết từng giai đoạn tham gia trước đây (customer_participations)
CREATE TABLE IF NOT EXISTS public.customer_participations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id UUID REFERENCES public.customers(id) ON DELETE CASCADE,
    customer_key TEXT,
    cccd TEXT,
    bhxh TEXT,
    type TEXT NOT NULL DEFAULT 'batbuoc',
    position TEXT,
    workplace TEXT,
    from_month INT NOT NULL DEFAULT 1,
    from_year INT NOT NULL DEFAULT 2020,
    to_month INT NOT NULL DEFAULT 12,
    to_year INT NOT NULL DEFAULT 2020,
    months INT NOT NULL DEFAULT 0,
    salary NUMERIC,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.8. Bảng bút toán tài chính quyết toán đợt nộp / thoái thu (financial_settlements)
CREATE TABLE IF NOT EXISTS public.financial_settlements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    record_id BIGINT REFERENCES public.records(id) ON DELETE CASCADE,
    batch_id UUID REFERENCES public.submission_batches(id) ON DELETE SET NULL,
    settlement_type TEXT NOT NULL DEFAULT 'clawback',
    amount NUMERIC NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    approved_by TEXT REFERENCES public.staff(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.9. Bảng nhật ký kiểm toán hệ thống bất biến (auditlogs)
CREATE TABLE IF NOT EXISTS public.auditlogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id TEXT,
    user_name TEXT,
    action TEXT NOT NULL,
    details TEXT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.10. Bảng ghi nhận lượt gọi RPC công khai để Rate-limit (public_rpc_call_log)
CREATE TABLE IF NOT EXISTS public.public_rpc_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    called_at TIMESTAMPTZ DEFAULT NOW()
);

-- ======================================================================
-- 3. TẠO INDEXES TỐI ƯU HIỆU NĂNG TRUY VẤN VÀ TÌM KIẾM TOÀN VĂN
-- ======================================================================

-- 3.1. B-Tree Indexes trên bảng records
CREATE INDEX IF NOT EXISTS idx_records_cccd ON public.records (cccd);
CREATE INDEX IF NOT EXISTS idx_records_bhxh ON public.records (bhxh);
CREATE INDEX IF NOT EXISTS idx_records_old_bhxh ON public.records (old_bhxh) WHERE old_bhxh IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_records_staff_id ON public.records (staff_id);
CREATE INDEX IF NOT EXISTS idx_records_batch_id ON public.records (batch_id);
CREATE INDEX IF NOT EXISTS idx_records_submission_batch_id ON public.records (submission_batch_id);
CREATE INDEX IF NOT EXISTS idx_records_submission_batch ON public.records (submission_batch);
CREATE INDEX IF NOT EXISTS idx_records_customer_id ON public.records (customer_id);
CREATE INDEX IF NOT EXISTS idx_records_customer_key ON public.records (customer_key);
CREATE INDEX IF NOT EXISTS idx_records_from_month_date ON public.records (from_month_date);
CREATE INDEX IF NOT EXISTS idx_records_to_month_date ON public.records (to_month_date);
CREATE INDEX IF NOT EXISTS idx_records_date_brin ON public.records USING BRIN (date);

-- 3.2. Composite Indexes phục vụ bộ lọc nghiệp vụ
CREATE INDEX IF NOT EXISTS idx_records_finance_query ON public.records (type, payment_status, action_type, date DESC);
CREATE INDEX IF NOT EXISTS idx_records_finance_filter_composite ON public.records (type, staff_id, payment_status, date DESC);
CREATE INDEX IF NOT EXISTS idx_records_finance_filter ON public.records (type, payment_status, date DESC);
CREATE INDEX IF NOT EXISTS idx_records_staff_date ON public.records (staff_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_records_batch_lookup ON public.records (submission_batch, is_submitted_bhxh);
CREATE INDEX IF NOT EXISTS idx_records_next_payment_sla ON public.records (next_payment, payment_status) WHERE payment_status != 'Đã hủy';
CREATE INDEX IF NOT EXISTS idx_records_lookup_perf ON public.records (bhxh, cccd) WHERE payment_status != 'Đã hủy';

-- 3.3. Idempotency Key chống trùng lặp giao dịch
CREATE UNIQUE INDEX IF NOT EXISTS idx_records_idempotency_key 
ON public.records (idempotency_key) 
WHERE idempotency_key IS NOT NULL AND idempotency_key != '';

-- 3.4. Indexes trên bảng customers & customer_participations
CREATE INDEX IF NOT EXISTS idx_customers_status_type ON public.customers (type, status, next_payment ASC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_customers_staff_lookup ON public.customers (staff_id, next_payment ASC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_customers_latest_date ON public.customers (latest_date DESC);
CREATE INDEX IF NOT EXISTS idx_cust_participations_cust_id ON public.customer_participations (customer_id);
CREATE INDEX IF NOT EXISTS idx_cust_participations_key ON public.customer_participations (customer_key);

-- 3.5. Indexes trên submission_batches, financial_settlements, staff, auditlogs, policies
CREATE INDEX IF NOT EXISTS idx_submission_batches_code ON public.submission_batches (batch_code);
CREATE INDEX IF NOT EXISTS idx_submission_batches_status ON public.submission_batches (status);
CREATE INDEX IF NOT EXISTS idx_submission_batches_created_by ON public.submission_batches (created_by);
CREATE INDEX IF NOT EXISTS idx_fin_settlements_record_id ON public.financial_settlements (record_id);
CREATE INDEX IF NOT EXISTS idx_fin_settlements_batch_id ON public.financial_settlements (batch_id);
CREATE INDEX IF NOT EXISTS idx_fin_settlements_type ON public.financial_settlements (settlement_type);
CREATE INDEX IF NOT EXISTS idx_staff_auth_user_id ON public.staff (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_staff_role ON public.staff (role, status);
CREATE INDEX IF NOT EXISTS idx_auditlogs_timestamp ON public.auditlogs (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_public_rpc_call_log_lookup ON public.public_rpc_call_log (action, ip_address, called_at DESC);
CREATE INDEX IF NOT EXISTS idx_policies_parameter_lookup ON public.policies (parameter_type, effective_date DESC, is_active);

-- 3.6. GIN Trigram Indexes cho tìm kiếm toàn văn siêu tốc (< 50ms)
CREATE INDEX IF NOT EXISTS idx_records_search_trgm 
ON public.records USING gin ((
  COALESCE(name, '') || ' ' || 
  COALESCE(cccd, '') || ' ' || 
  COALESCE(bhxh, '') || ' ' || 
  COALESCE(old_bhxh, '') || ' ' || 
  COALESCE(phone, '')
) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_customers_search_trgm 
ON public.customers USING gin ((
  COALESCE(name, '') || ' ' || 
  COALESCE(cccd, '') || ' ' || 
  COALESCE(bhxh, '') || ' ' || 
  COALESCE(old_bhxh, '') || ' ' || 
  COALESCE(phone, '')
) gin_trgm_ops);

-- ======================================================================
-- 4. ĐỊNH NGHĨA CÁC VIEWS TỔNG HỢP & UNIFIED VIEW
-- ======================================================================

-- 4.1. View CRM Customers qua Master Table
DROP VIEW IF EXISTS public.crm_customers CASCADE;
CREATE OR REPLACE VIEW public.crm_customers 
WITH (security_invoker = true) AS
SELECT 
    r.id,
    r.date,
    c.name,
    c.cccd,
    c.phone,
    c.address,
    c.bhxh,
    c.old_bhxh,
    r.type,
    r.sub_type,
    r.wage,
    r.months,
    r.support_pct,
    r.amount,
    c.status,
    r.payment_status,
    r.notes,
    r.staff_id,
    r.from_month,
    r.to_month,
    r.from_month_date,
    r.to_month_date,
    r.base_premium,
    r.nn_support_pct,
    r.nn_support_amount,
    r.dp_support_pct,
    r.dp_support_amount,
    r.effective_date,
    r.target_date,
    COALESCE(r.next_payment, c.next_payment) AS next_payment,
    c.next_payment_bhxh,
    c.next_payment_bhyt,
    c.has_bhxh,
    c.has_bhyt,
    r.household_id,
    r.members,
    r.recv_name,
    r.recv_phone,
    r.recv_address,
    r.is_submitted_bhxh,
    r.submission_batch,
    r.submission_batch_id,
    r.submitted_date,
    r.action_type,
    c.dob,
    c.gender,
    c.nation,
    c.email,
    r.income,
    r.method,
    r.discount_amount,
    r.penalty_amount,
    r.created_at,
    r.is_adjustment,
    r.original_record_id,
    r.adjustment_reason,
    r.refund_type,
    r.decision_number,
    r.decision_date,
    r.refund_method,
    r.refund_beneficiary_name,
    r.refund_beneficiary_account,
    r.refund_beneficiary_bank,
    r.hospital_code,
    r.hospital_name,
    c.customer_key,
    c.id AS customer_id,
    c.prior_periods,
    c.prior_voluntary_months,
    c.prior_compulsory_months,
    c.prior_participation_notes
FROM public.customers c
JOIN public.records r ON c.latest_record_id = r.id;

-- 4.2. View Lịch sử Giao dịch Khách hàng (v_customer_transactions)
DROP VIEW IF EXISTS public.v_customer_transactions CASCADE;
CREATE OR REPLACE VIEW public.v_customer_transactions 
WITH (security_invoker = true) AS
SELECT 
    r.id AS transaction_id,
    r.date AS transaction_date,
    r.type AS service_type,
    r.action_type,
    r.months AS duration_months,
    r.from_month,
    r.to_month,
    r.amount AS transaction_amount,
    r.payment_status,
    r.staff_id,
    r.is_submitted_bhxh,
    r.submission_batch,
    r.submission_batch_id,
    r.notes AS transaction_notes,
    c.id AS customer_id,
    c.customer_key,
    c.name AS customer_name,
    c.cccd AS customer_cccd,
    c.bhxh AS customer_bhxh,
    c.phone AS customer_phone,
    c.address AS customer_address,
    c.dob AS customer_dob,
    c.gender AS customer_gender,
    c.total_contributions,
    c.total_amount_paid,
    c.next_payment
FROM public.records r
LEFT JOIN public.customers c ON (r.customer_id = c.id OR r.customer_key = c.customer_key)
ORDER BY r.date DESC;

-- 4.3. View Hồ sơ Chuẩn hóa Đồng bộ (v_records_unified - 100% snake_case)
DROP VIEW IF EXISTS public.v_records_unified CASCADE;
CREATE OR REPLACE VIEW public.v_records_unified 
WITH (security_invoker = true) AS
SELECT 
    r.id,
    r.customer_id,
    r.customer_key,
    r.staff_id,
    r.batch_id,
    r.submission_batch_id,
    r.submission_batch,
    r.is_submitted_bhxh,
    r.submitted_date,
    r.decision_date,
    r.type AS insurance_type,
    r.sub_type,
    r.action_type,
    r.name,
    r.cccd,
    r.phone,
    r.bhxh,
    r.old_bhxh,
    r.dob,
    r.gender,
    r.nation,
    r.address,
    r.wage,
    r.income,
    r.months,
    r.from_month,
    r.to_month,
    r.from_month_date,
    r.to_month_date,
    r.effective_date,
    r.target_date,
    r.next_payment,
    r.base_premium,
    COALESCE(r.nn_support_pct, 0) AS nn_support_pct,
    COALESCE(r.nn_support_amount, 0) AS nn_support_amount,
    COALESCE(r.dp_support_pct, 0) AS dp_support_pct,
    COALESCE(r.dp_support_amount, 0) AS dp_support_amount,
    COALESCE(r.discount_amount, 0) AS discount_amount,
    COALESCE(r.penalty_amount, 0) AS penalty_amount,
    r.amount,
    r.commission,
    r.status,
    r.payment_status,
    r.method,
    r.base_salary_snapshot,
    r.poverty_standard_snapshot,
    r.policy_version_id,
    r.is_adjustment,
    r.original_record_id,
    r.adjustment_reason,
    r.refund_type,
    r.created_at,
    r.updated_at
FROM public.records r;

-- ======================================================================
-- 5. KHỞI TẠO DỮ LIỆU CẤU HÌNH MẶC ĐỊNH (SEED DATA)
-- ======================================================================

-- 5.1. Dữ liệu mặc định bảng settings (id = 1)
INSERT INTO public.settings (
    id, comm_bhxh_new, comm_bhxh_renew, comm_bhyt_new, comm_bhyt_renew,
    comm_bhxh, comm_bhyt, investment_rate, base_salary, poverty_standard, cpi_index,
    agency_name, agency_code, bank_bin, bank_id, bank_name, account_number, account_holder, qr_template
) VALUES (
    1, 5, 3, 5, 3, 5, 5, 0.31, 2340000, 1500000,
    '{"2026": 1.0, "2025": 1.0, "2024": 1.03, "2023": 1.07, "2022": 1.11, "2021": 1.14, "2020": 1.16, "2019": 1.20, "2018": 1.23, "2017": 1.28, "2016": 1.32, "2015": 1.36, "2014": 1.36, "2013": 1.42, "2012": 1.51, "2011": 1.65, "2010": 1.96, "2009": 2.14, "2008": 2.29, "2007": 2.81, "2006": 3.05, "2005": 3.27, "2004": 3.54, "2003": 3.81, "2002": 3.94, "2001": 4.09, "2000": 4.07, "1999": 4.01, "1998": 4.18, "1997": 4.50, "1996": 4.91, "1994": 5.81}'::jsonb,
    'Đại lý thu BHXH Sông Mã', 'VSS-SM-001', '970422', 'MB', 'MB (Ngân hàng Quân Đội)', '0868123456', 'DAI LY THU BHXH SONG MA', 'compact2'
)
ON CONFLICT (id) DO UPDATE 
SET base_salary = EXCLUDED.base_salary,
    poverty_standard = EXCLUDED.poverty_standard,
    agency_name = EXCLUDED.agency_name,
    bank_bin = EXCLUDED.bank_bin,
    account_number = EXCLUDED.account_number;

-- 5.2. Khởi tạo 5 nhóm tham số chính sách cốt lõi vào bảng policies
-- 5.2.1. Mức lương cơ sở: NĐ 73/2024 (2.340.000đ)
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'base_salary', 'Nghị định 73/2024/NĐ-CP', '2340000'::jsonb, '2024-07-01'::date, false, 
       'Quy định mức lương cơ sở đối với cán bộ, công chức, viên chức và lực lượng vũ trang (2.340.000 đồng/tháng)',
       'Quy định mức lương cơ sở đối với cán bộ, công chức, viên chức và lực lượng vũ trang (2.340.000 đồng/tháng)'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'base_salary' AND name = 'Nghị định 73/2024/NĐ-CP'
);

-- 5.2.2. Mức lương cơ sở: NĐ 161/2026 (2.530.000đ)
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'base_salary', 'Nghị định số 161/2026/NĐ-CP', '2530000'::jsonb, '2026-07-01'::date, true, 
       'NĐ 161/2026/NĐ-CP ngày 15/5/2026 quy định mức lương cơ sở mới và chế độ tiền thưởng (2.530.000 đồng/tháng)',
       'NĐ 161/2026/NĐ-CP ngày 15/5/2026 quy định mức lương cơ sở mới và chế độ tiền thưởng (2.530.000 đồng/tháng)'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'base_salary' AND name = 'Nghị định số 161/2026/NĐ-CP'
);

-- 5.2.3. Chuẩn nghèo nông thôn: NĐ 07/2021/NĐ-CP (1.500.000đ)
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'poverty_standard', 'Chuẩn nghèo nông thôn 2026', '1500000'::jsonb, '2026-01-01'::date, true, 
       'Điều 3 Nghị định 07/2021/NĐ-CP quy định chuẩn nghèo đa chiều giai đoạn 2022-2025 và áp dụng 2026 (1.500.000 đồng/tháng)',
       'Điều 3 Nghị định 07/2021/NĐ-CP quy định chuẩn nghèo đa chiều giai đoạn 2022-2025 và áp dụng 2026 (1.500.000 đồng/tháng)'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'poverty_standard' AND name = 'Chuẩn nghèo nông thôn 2026'
);

-- 5.2.4. Tỷ lệ Hoa hồng: Quyết định 11/QĐ-BHXH (Cũ)
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'commission', 'Quyết định 11/QĐ-BHXH (Cũ)', '{"commBHXHNew": 5, "commBHYTNew": 5, "commBHXHRenew": 3, "commBHYTRenew": 3}'::jsonb, '2026-01-01'::date, false, 
       'Quyết định 11/QĐ-BHXH mức chi thù lao đại lý: BHXH mới 5%, gia hạn 3%; BHYT mới 5%, gia hạn 3%',
       'Quyết định 11/QĐ-BHXH mức chi thù lao đại lý: BHXH mới 5%, gia hạn 3%; BHYT mới 5%, gia hạn 3%'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'commission' AND name = 'Quyết định 11/QĐ-BHXH (Cũ)'
);

-- 5.2.5. Tỷ lệ Hoa hồng: Cài đặt Tỷ lệ Hoa hồng đại lý 2026
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'commission', 'Cài đặt Tỷ lệ Hoa hồng đại lý 2026', '{"commBHXHNew": 15, "commBHYTNew": 9, "commBHXHRenew": 9, "commBHYTRenew": 5}'::jsonb, '2026-08-01'::date, true, 
       'Cơ chế tỷ lệ hoa hồng đại lý mới áp dụng từ tháng 08/2026: BHXH mới 15%, gia hạn 9%; BHYT mới 9%, gia hạn 5%',
       'Cơ chế tỷ lệ hoa hồng đại lý mới áp dụng từ tháng 08/2026: BHXH mới 15%, gia hạn 9%; BHYT mới 9%, gia hạn 5%'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'commission' AND name = 'Cài đặt Tỷ lệ Hoa hồng đại lý 2026'
);

-- 5.2.6. Lãi suất đầu tư quỹ: 0.31%/tháng
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'investment_rate', 'Quyết định điều chỉnh Lãi suất đầu tư quỹ 2026', '0.31'::jsonb, '2026-01-01'::date, true, 
       'Công văn 151/BHXH-ĐTQ và Công văn 59/TB-BHXH lãi suất đầu tư quỹ 0.31%/tháng',
       'Công văn 151/BHXH-ĐTQ và Công văn 59/TB-BHXH lãi suất đầu tư quỹ 0.31%/tháng'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'investment_rate' AND name = 'Quyết định điều chỉnh Lãi suất đầu tư quỹ 2026'
);

-- 5.2.7. Hệ số trượt giá: Thông tư 01/2025/TT-BLĐTBXH
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'cpi_index', 'Thông tư điều chỉnh Hệ số trượt giá (JSON BHXH) 2025', 
       '{"1994": 5.81, "1995": 4.91, "1996": 4.65, "1997": 4.5, "1998": 4.18, "1999": 4.01, "2000": 4.07, "2001": 4.09, "2002": 3.94, "2003": 3.81, "2004": 3.54, "2005": 3.27, "2006": 3.05, "2007": 2.81, "2008": 2.29, "2009": 2.14, "2010": 1.96, "2011": 1.65, "2012": 1.51, "2013": 1.42, "2014": 1.36, "2015": 1.36, "2016": 1.32, "2017": 1.28, "2018": 1.23, "2019": 1.2, "2020": 1.16, "2021": 1.14, "2022": 1.11, "2023": 1.07, "2024": 1.03, "2025": 1}'::jsonb, 
       '2025-01-01'::date, false, 
       'Thông tư số 01/2025/TT-BLĐTBXH ngày 10/1/2025 điều chỉnh tiền lương và thu nhập đã đóng BHXH',
       'Thông tư số 01/2025/TT-BLĐTBXH ngày 10/1/2025 điều chỉnh tiền lương và thu nhập đã đóng BHXH'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'cpi_index' AND name = 'Thông tư điều chỉnh Hệ số trượt giá (JSON BHXH) 2025'
);

-- 5.2.8. Hệ số trượt giá: Công văn 340/BHXH-CSXH 2026
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'cpi_index', 'Công văn 340/BHXH-CSXH đ/c Hệ số trượt giá 2026', 
       '{"1994": 5.81, "1995": 4.91, "1996": 4.65, "1997": 4.5, "1998": 4.18, "1999": 4.01, "2000": 4.07, "2001": 4.09, "2002": 3.94, "2003": 3.81, "2004": 3.54, "2005": 3.27, "2006": 3.05, "2007": 2.81, "2008": 2.29, "2009": 2.14, "2010": 1.96, "2011": 1.65, "2012": 1.51, "2013": 1.42, "2014": 1.36, "2015": 1.36, "2016": 1.32, "2017": 1.28, "2018": 1.23, "2019": 1.2, "2020": 1.16, "2021": 1.14, "2022": 1.11, "2023": 1.07, "2024": 1.03, "2025": 1, "2026": 1}'::jsonb, 
       '2026-01-01'::date, true, 
       'Hệ số trượt giá năm 2026 theo Công văn 340/BHXH-CSXH',
       'Hệ số trượt giá năm 2026 theo Công văn 340/BHXH-CSXH'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'cpi_index' AND name = 'Công văn 340/BHXH-CSXH đ/c Hệ số trượt giá 2026'
);

-- 5.2.9. Phân quyền vai trò RBAC mặc định
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'rbac_role_permissions', 'Bảng Phân Quyền Vai Trò RBAC', 
       '{"Nhân viên": ["calc", "lookup", "manage", "customers", "participation", "reports", "finance", "support", "batch_management"], "Quản lý": ["calc", "lookup", "manage", "customers", "participation", "reports", "finance", "support", "policy_management", "agency_management", "batch_management"], "Admin": ["calc", "lookup", "manage", "customers", "participation", "reports", "finance", "support", "policy_management", "agency_management", "staff_management", "permissions_management", "batch_management", "system_settings", "audit_log"]}'::jsonb,
       '2026-01-01'::date, true, 
       'Ma trận phân quyền vai trò nhân sự đại lý BHXH Sông Mã',
       'Ma trận phân quyền vai trò nhân sự đại lý BHXH Sông Mã'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'rbac_role_permissions'
);

-- 5.2.10. Phân quyền đặc cách riêng theo nhân viên mặc định
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'rbac_user_overrides', 'Phân Quyền Đặc Cách Riêng Theo Nhân Viên', 
       '{}'::jsonb,
       '2026-01-01'::date, true, 
       'Cấu hình phân quyền đặc cách riêng (User Overrides) cho từng cán bộ thu',
       'Cấu hình phân quyền đặc cách riêng (User Overrides) cho từng cán bộ thu'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'rbac_user_overrides'
);

-- 5.2.11. Cấu hình VietQR thanh toán mặc định
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'payment_vietqr', 'Cấu hình VietQR Đại lý', 
       '{"bankBin": "970422", "bankId": "MB", "bankName": "MB (Ngân hàng Quân Đội)", "accountNumber": "0868123456", "accountHolder": "DAI LY THU BHXH SONG MA", "agencyName": "Đại lý thu BHXH Sông Mã", "agencyCode": "VSS-SM-001", "qrTemplate": "compact2"}'::jsonb,
       '2026-01-01'::date, true, 
       'Cấu hình tài khoản ngân hàng thụ hưởng VietQR NAPAS 247 của Đại lý',
       'Cấu hình tài khoản ngân hàng thụ hưởng VietQR NAPAS 247 của Đại lý'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'payment_vietqr'
);

-- 5.2.12. Cấu hình thông số in ấn và mẫu biểu chuẩn Nghị định 30/2020/NĐ-CP
INSERT INTO public.policies (parameter_type, name, value, effective_date, is_active, notes, description)
SELECT 'report_print_settings', 'Cấu hình Thông số In ấn & Báo cáo', 
       '{"agencyName": "Đại lý thu BHXH Sông Mã", "parentAgencyName": "BHXH HUYỆN SÔNG MÃ - TỈNH SƠN LA", "managerName": "Lò Văn Sung", "reportLocation": "Sông Mã", "controllerName": "", "managerTitle": "Thủ trưởng đơn vị", "creatorTitle": "Người lập biểu", "controllerTitle": "Kế toán trưởng"}'::jsonb,
       '2026-01-01'::date, true, 
       'Thông số in ấn và mẫu biểu chuẩn Nghị định 30/2020/NĐ-CP',
       'Thông số in ấn và mẫu biểu chuẩn Nghị định 30/2020/NĐ-CP'
WHERE NOT EXISTS (
  SELECT 1 FROM public.policies WHERE parameter_type = 'report_print_settings'
);
